[package]
name = "nicegal-cli"
version = "0.3.0"
authors = ["bep"]
license = "AGPL-3.0-only"
edition = "2024"
description = "Command-line interface for nicegal-server"
repository = "https://github.com/centuryofimage/nicegal-server"
keywords = ["ocr", "image", "paddleocr"]
categories = ["command-line-utilities", "multimedia::images"]

[[bin]]
name = "nicegal-cli"
path = "src/main.rs"

[features]
default = ["regex"]
regex = ["nicegal-core/regex"]

[dependencies]
anyhow = "1.0.104"
camino = "1.2.5"
clap = { version = "4.6.6", features = ["cargo", "wrap_help", "env"] }
dirs = "7.0.0"
nicegal-core = { path = "..", default-features = false }
