use std::fmt;
use std::str::FromStr;

/// A text embedding model supported by this build.
///
/// Its identifier is persisted alongside generated vectors. Add a variant here with its stable
/// identifier and dimensions, then add its inference-backend mapping in `fastembed.rs`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum TextEmbeddingModel {
    /// BAAI's 384-dimensional English BGE small v1.5 model.
    #[default]
    BgeSmallEnV15,
}

impl TextEmbeddingModel {
    /// Stable identifier persisted with vectors generated by this model.
    pub const fn id(self) -> &'static str {
        match self {
            Self::BgeSmallEnV15 => "BAAI/bge-small-en-v1.5",
        }
    }

    /// Width of vectors generated by this model.
    pub const fn dimensions(self) -> usize {
        match self {
            Self::BgeSmallEnV15 => 384,
        }
    }
}

impl fmt::Display for TextEmbeddingModel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.id())
    }
}

impl FromStr for TextEmbeddingModel {
    type Err = ParseTextEmbeddingModelError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "BAAI/bge-small-en-v1.5" => Ok(Self::BgeSmallEnV15),
            _ => Err(ParseTextEmbeddingModelError(value.to_owned())),
        }
    }
}

/// Error returned when a text embedding model identifier is not supported by this build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseTextEmbeddingModelError(String);

impl fmt::Display for ParseTextEmbeddingModelError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "unsupported text embedding model {:?}; supported models: {}",
            self.0,
            TextEmbeddingModel::BgeSmallEnV15
        )
    }
}

impl std::error::Error for ParseTextEmbeddingModelError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_model_has_stable_persisted_metadata() {
        let model = TextEmbeddingModel::default();
        assert_eq!(model, TextEmbeddingModel::BgeSmallEnV15);
        assert_eq!(model.id(), "BAAI/bge-small-en-v1.5");
        assert_eq!(model.dimensions(), 384);
        assert_eq!(model.to_string(), model.id());
    }

    #[test]
    fn parsing_accepts_persisted_ids_and_rejects_unknown_models() {
        assert_eq!(
            "BAAI/bge-small-en-v1.5".parse::<TextEmbeddingModel>(),
            Ok(TextEmbeddingModel::BgeSmallEnV15)
        );
        assert!("some-real-model".parse::<TextEmbeddingModel>().is_err());
    }
}
